framework:
  secret: '%env(APP_SECRET)%'

  session:
    enabled: true
    cookie_samesite: lax
    cookie_secure: false
    cookie_httponly: true
    cookie_path: '/'

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
